server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://116.198.233.53:3306/library?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/lib?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456

  redis:
    host: 116.198.233.53
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-active: 50

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#???
alipay:
  appId: 9021000135680405
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDG05sfrf8G6KFyJrxrO6EYxDz4X8LG768aKDkrA02oBBVfVsDbjhq5yYNHRpV9rifaTBPwFNXPHN3r8wrm99DdsoQWfG3w9gmFYLvIkMM2NR3c10ZfSHrhQ36xnQk2Zm+5RlwkTaQgG6LH8NLHompwX++dPecKe2rxeo7N5WmqEzdMRpXk/kGd7iqd2GCNewKqMVKsUUg9+pvpt8jQDdbYFgu1g9eX8b17B295WcRO0+gDRHV0+sCc0woRsF6/rPwaTxW+7Lgd2+ZSolixBXdZ/uC0WjagS8CNQKycShmoCHjmjn9Frg2sLbD9wLaN+qQaALR6u8PEfkFLJeWcv5YlAgMBAAECggEBAISd5e0WgHFaPz1Fiw23YzeCxOwh62gHvPKke6Ut+eEkgCDsW4zWVwsu1up2sQV4YUqgzfen3gjcR0W3AcGW7/C/vozFCAvd//G/2ODpddu1SCriSCUL0jJoc5wCk39+iey5eoIYa22jIUtdXSodMgOsacWm4XFDasyQo6m/6F+wbdX4DmWIGeQzCXltJdHh/RzW5Zin7m76fn+j3SjPd2m2dnpn+tIBDM8g+XBCuTmkH0SSnC1ZrJJaiUXzcjDuHPbadyEimK6nNH7L6iNwXbDbTFQ/QHlxXzZiPLvhsqpADXKDw3XIYQ9rS1Y9qRITD35sF5EJySSlYWT758Ud3q0CgYEA8brYheeAvZSEYmApoupcMdD2sypxCfVzbfqFy4V6QnE2I1BLtrSl1CuH+9vgA1uwaeZXv0BP2odZnK/fSkbT5I0kF1CPToydjOHHOG7z8HcKdBfNsmv+AY/SZyzSGcryi5WlV7LuMuqtluh6836Zk0kdMDn2smcKe7TGgHHGJjMCgYEA0pBh3InXZyO+cabRjLZ6Een46vOsj2mL95ea6FzNwXQ12VziCFCJT45ZjTlFn4r2mp+mybssBU3Y43MivBLZ+5fgcrY/asQ2WUPgZap0nDnUEpEDp4gjgYjW2pLGO05ihj8MLQc3WtqKSx2Nrq5xjc5O+bU0TYluO0BtsSp/CkcCgYEA563IsC39ObYKW68GuNodmrFIgNeAl6bkBthBO5qmXt/an2Xp6yageQVvw3gs74sFPbpDB05AOpXW0VHOlIXlt/t+R8oyT3p91fTe17ufmSy+nB3kS8ktHZoWckSG6amVZSr72V3o5mv+C9CtZopD7uH4U6x6QOp5Ja9RQPHKk/kCgYAsj0t2bWE9PW43BPOBkLhChD4eEpUpAFAThGzO0ZzlXJ9ssWBQHCMCyAAhh8Y5HiJT1IdqV4bYVIIamCn4nRCuUpS4EeNXx9AskdWyDiGBUieUCkY4tPG2nuvA86CpukvVVxBPkyBexLLRdJ6gIeB7/vXtmDBKXFQMi/TqsjCSTwKBgQCbyDFge63H3bAdNuN1s03NgQK2+UW8VtOYa3s+J2WlEb+VoX73Idr4qUwpo+/WfOu8OPH1FmQ3WlV8AtwFWR5XMrAGvDBTuhBGCi6CbDPCmh9ZbE4WEKNN6G7U/H8Dm52/Jf6+MdUSworRVQ63vNIEZh1f99pUUKQKaq34Ie3xvg==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn3MGff13SqCo/x6F2BJT6WqWgkDdHl7mJvZUNAudaphZynyViK64D4x5bwN/bACaOffhh9I1IRLd83V0bf6c/5KrRHylaBf1Zn420nC/QsIarUVmRykebMyS5JQcce2IDFFJRNrtGfO7iH0faUboe5XQkQ1SddZ4wRJ+ViiDK/uUL6jke5k8TWS/QGCyeicaSq10SbRngDAIL1TmQezyJmiVJzXuxrBDRKk4Z1YOc9YqSv1hLL9nJm+NW/0nytLa4xNnuiDU2R2FCFIBmrW8WpmXS/KzvpgSh7RoJI6jDQdy1YJJXgvGE1omS1750MwJlGcUAmIVwnC00OIiEEOlwwIDAQAB
  notifyUrl: http://n8dxf5.natappfree.cc/alipay/notify
  returnUrl: http://localhost:9876/fine

#natapp -authtoken=d0e1d6f12bd64f73
#iflhrh3053@sandbox.com
#111111